// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: email_template.proto

package ms_email_grpc_api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ETListAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ETListAllRequest) Reset() {
	*x = ETListAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_email_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ETListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETListAllRequest) ProtoMessage() {}

func (x *ETListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETListAllRequest.ProtoReflect.Descriptor instead.
func (*ETListAllRequest) Descriptor() ([]byte, []int) {
	return file_email_template_proto_rawDescGZIP(), []int{0}
}

type ETListAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ETList []*EmailTempate `protobuf:"bytes,1,rep,name=ETList,proto3" json:"ETList,omitempty"`
}

func (x *ETListAllResponse) Reset() {
	*x = ETListAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_email_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ETListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETListAllResponse) ProtoMessage() {}

func (x *ETListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETListAllResponse.ProtoReflect.Descriptor instead.
func (*ETListAllResponse) Descriptor() ([]byte, []int) {
	return file_email_template_proto_rawDescGZIP(), []int{1}
}

func (x *ETListAllResponse) GetETList() []*EmailTempate {
	if x != nil {
		return x.ETList
	}
	return nil
}

type EmailTempate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *EmailTempate) Reset() {
	*x = EmailTempate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_email_template_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailTempate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTempate) ProtoMessage() {}

func (x *EmailTempate) ProtoReflect() protoreflect.Message {
	mi := &file_email_template_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTempate.ProtoReflect.Descriptor instead.
func (*EmailTempate) Descriptor() ([]byte, []int) {
	return file_email_template_proto_rawDescGZIP(), []int{2}
}

func (x *EmailTempate) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_email_template_proto protoreflect.FileDescriptor

var file_email_template_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x54, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x11, 0x45, 0x54,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x06, 0x45, 0x54, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x61, 0x74, 0x65, 0x52, 0x06, 0x45,
	0x54, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65,
	0x6d, 0x70, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x3b, 0x6d,
	0x73, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_email_template_proto_rawDescOnce sync.Once
	file_email_template_proto_rawDescData = file_email_template_proto_rawDesc
)

func file_email_template_proto_rawDescGZIP() []byte {
	file_email_template_proto_rawDescOnce.Do(func() {
		file_email_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_email_template_proto_rawDescData)
	})
	return file_email_template_proto_rawDescData
}

var file_email_template_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_email_template_proto_goTypes = []interface{}{
	(*ETListAllRequest)(nil),  // 0: email.template.ETListAllRequest
	(*ETListAllResponse)(nil), // 1: email.template.ETListAllResponse
	(*EmailTempate)(nil),      // 2: email.template.EmailTempate
}
var file_email_template_proto_depIdxs = []int32{
	2, // 0: email.template.ETListAllResponse.ETList:type_name -> email.template.EmailTempate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_email_template_proto_init() }
func file_email_template_proto_init() {
	if File_email_template_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_email_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ETListAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_email_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ETListAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_email_template_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailTempate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_email_template_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_email_template_proto_goTypes,
		DependencyIndexes: file_email_template_proto_depIdxs,
		MessageInfos:      file_email_template_proto_msgTypes,
	}.Build()
	File_email_template_proto = out.File
	file_email_template_proto_rawDesc = nil
	file_email_template_proto_goTypes = nil
	file_email_template_proto_depIdxs = nil
}
